# Generated by Django 4.2 on 2023-05-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(max_length=1000)),
                ("desc", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("val", models.FloatField()),
                ("date", models.DateTimeField()),
                ("ind_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="indicators.indicator")),
                ("uid", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
