# Generated by Django 4.2 on 2023-05-05 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0002_alter_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
