# Generated by Django 4.2 on 2023-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0004_alter_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.UniqueConstraint(fields=("ind_id", "date"), name="unique_log"),
        ),
    ]
