# Generated by Django 4.2 on 2023-05-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0005_alter_indicator_name_log_unique_log"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="log",
            name="unique_log",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="ind_id",
            new_name="indicator_id",
        ),
        migrations.AlterField(
            model_name="indicator",
            name="unit",
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.UniqueConstraint(fields=("indicator_id", "date"), name="unique_log"),
        ),
    ]
