# Generated by Django 4.2 on 2023-05-06 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0006_remove_log_unique_log_rename_ind_id_log_indicator_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="indicator_id",
            new_name="indicator",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="uid",
            new_name="user",
        ),
    ]
