default_stages: [commit]

default_language_version:
  python: python3.11

repos:

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: make-badges
        name: make-badges
        entry: src/auth/get_badges.py
        language: script
        pass_filenames: false
        verbose: true

  - repo: local

    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

  - repo: local

    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
