version: "3.9"

services:

  api:
    build:
      dockerfile: src/auth/Dockerfile
      args:
        SRC_NAMESPACE: $SRC_NAMESPACE

    ports:
        - "${API_PORT_EXTERNAL}:8000/tcp"

  db:
    build:
      dockerfile: db/Dockerfile

    ports:
        - "${PG_PORT_EXTERNAL}:5432/tcp"
