version: "3.9"

services:

  api:
    extends:
      service: api
      file: src/auth/docker-compose.yml

    env_file: $PWD/.env

    volumes:
      # папка для БД и ключей
      - ./dbs:/home/appuser/dbs
      # удобства внутри контейнера
      - ./.history:/home/appuser/commandhistory/
      - ./.bashrc:/home/appuser/.bashrc

    networks:
      - compose-net

  db:
    extends:
      service: db
      file: db/docker-compose.yml

    env_file: $PWD/.env

    volumes:
      - ./.history:/home/appuser/commandhistory/
      - ./.bashrc:/home/appuser/.bashrc
      - ./$DBS/$POSTGRES_DB_FOLDER${SUFFIX}/:/var/lib/postgresql/data/

    networks:
      - compose-net

networks:
  compose-net:
    name: $NET_NAME
