# Generated by Django 4.2 on 2023-04-29 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Images",
            new_name="Image",
        ),
    ]
