version: "3.9"

services:

  api:

    restart: unless-stopped
    container_name: api${SUFFIX:?err}
    hostname: api${SUFFIX:?err}

    tty: true
    init: true

    environment:
      - DBS
      - DEBUG
      - RELOAD
      - TESTING
      - TERM=xterm-256color
